[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
ffi = false
evm_version = "paris"

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}", chain = 80002 }
